### PR TITLE
Change "repository" to "directory"

### PR DESCRIPTION
**Pull request by tobscure**
"Directory" or "folder" is a more correct word in English for this :)

### CODE REVIEW

**Comment by tobscure** [comment]
Hold on, let me rebase this so you can merge

**Comment by tobscure** [comment]
There we go.

**Comment by maelsoucaze** [comment]
Thanks! I don't know why I'm using repository all the time since I'm using GitHub. I'm shocked!

**Comment by tobscure** [comment]
Oops, I think this broke the readme D: I'll try and find time to send a fix PR tomorrow, if you don't beat me to it. Sorry!

**Comment by maelsoucaze** [comment]
Haha, saw that at work. No problem, I will fix it once at home. :D

**Pull request merged**
